// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr3SxAMNj39ndy0S0ElsslLm44iuODFRc',
    appId: '1:1027094878610:android:7dd75d152e3a32292c494b',
    messagingSenderId: '1027094878610',
    projectId: 'next-gen-app-udyam',
    databaseURL: 'https://next-gen-app-udyam-default-rtdb.firebaseio.com',
    storageBucket: 'next-gen-app-udyam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKzcIBd4FxTgs9Qj2-zngln-IY7rte1Ds',
    appId: '1:1027094878610:ios:3ae55544b8327e122c494b',
    messagingSenderId: '1027094878610',
    projectId: 'next-gen-app-udyam',
    databaseURL: 'https://next-gen-app-udyam-default-rtdb.firebaseio.com',
    storageBucket: 'next-gen-app-udyam.firebasestorage.app',
    iosBundleId: 'com.udyam.nextgen.next-gen',
  );
}
